title: Carlos Barreto
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#url: https://carlobar.github.io
#baseurl: 
logo: /resume/profile-19_b.jpg
remote_theme: pages_theme/minimal@v0.2.0
plugins: 
- jekyll-remote-theme
