title: Carlos Barreto
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
# url: https://carlobar.github.io
# baseurl: 
# logo: /resume/profile-19_b.jpg
# logo: /assets/img/profile-19_b.jpg
logo: /assets/img/logo.png
description: description
remote_theme: pages_theme/minimal@v0.2.0
plugins: 
- jekyll-remote-theme
